<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Errandy.Api\Errandy.Api.csproj" />
    <ProjectReference Include="..\Errandy.Application\Errandy.Application.csproj" />
    <ProjectReference Include="..\Errandy.Domain\Errandy.Domain.csproj" />
    <ProjectReference Include="..\Errandy.Infrastructure\Errandy.Infrastructure.csproj" />
  </ItemGroup>
	
</Project>
